server:
  port: 8088

dubbo:
  application:
    # dubbo admin中消费者名称
    name: dubbo-springboot-consumer
  # 应用所属者
  owner: Jessy Heung
  # 应用所属组织
  organization: Jessy Heung
  registry:
    id: zookeeper-registry
    # 注册中心协议
    protocol: zookeeper
    # 注册中心地址 此处为本地 zk 注册
    address: zookeeper://127.0.0.1:2181

  # dubbo协议在20880端口暴露服务
  # 协议名称
  protocol:
    name: dubbo
    # 协议端口
    port: 20880
    # 协议访问log
    accesslog: dubbo-access.log
  # 重试次数
  provider:
    retries: 0
    # 超时时间
    timeout: 3000
  # 注册监控中心
  monitor:
    protocol: registry